# INTENTIONAL FAKE SECRET FOR CLASS PROJECT
AWS_ACCESS_KEY_ID = "AKIAFAKEFAKEFAKEFAKE"

# INTENTIONAL FAKE SECRET FOR CLASS PROJECT
AWS_SECRET_ACCESS_KEY = "fakeSecretKey1234567890fakeSecretKey"

# INTENTIONAL FAKE SECRET FOR CLASS PROJECT
DB_PASSWORD = "SuperFakePassword123!"

# INTENTIONAL FAKE SECRET FOR CLASS PROJECT
API_TOKEN = "fake-api-token-xyz-123"

# INTENTIONAL FAKE SECRET FOR CLASS PROJECT
PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----FAKEFAKEFAKE-----END PRIVATE KEY-----"

# idk
YUH = "YUHHH"


def main():
    print("This is a demo app with FAKE secrets for git-secrets + SARIF project.")


if __name__ == "__main__":
    main()
